// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package cn.lcdiao.proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.lcdiao.proto.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *由StudentResponse组成的集合
   * </pre>
   *
   * <code>repeated .cn.lcdiao.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<cn.lcdiao.proto.StudentResponse> 
      getStudentResponseList();
  /**
   * <pre>
   *由StudentResponse组成的集合
   * </pre>
   *
   * <code>repeated .cn.lcdiao.proto.StudentResponse studentResponse = 1;</code>
   */
  cn.lcdiao.proto.StudentResponse getStudentResponse(int index);
  /**
   * <pre>
   *由StudentResponse组成的集合
   * </pre>
   *
   * <code>repeated .cn.lcdiao.proto.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <pre>
   *由StudentResponse组成的集合
   * </pre>
   *
   * <code>repeated .cn.lcdiao.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends cn.lcdiao.proto.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <pre>
   *由StudentResponse组成的集合
   * </pre>
   *
   * <code>repeated .cn.lcdiao.proto.StudentResponse studentResponse = 1;</code>
   */
  cn.lcdiao.proto.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
