// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package cn.lcdiao.proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.lcdiao.proto.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *由StudentResponse组成的集合
   * </pre>
   *
   * <code>repeated .cn.lcdiao.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<StudentResponse>
      getStudentResponseList();
  /**
   * <pre>
   *由StudentResponse组成的集合
   * </pre>
   *
   * <code>repeated .cn.lcdiao.proto.StudentResponse studentResponse = 1;</code>
   */
  StudentResponse getStudentResponse(int index);
  /**
   * <pre>
   *由StudentResponse组成的集合
   * </pre>
   *
   * <code>repeated .cn.lcdiao.proto.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <pre>
   *由StudentResponse组成的集合
   * </pre>
   *
   * <code>repeated .cn.lcdiao.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends StudentResponseOrBuilder>
      getStudentResponseOrBuilderList();
  /**
   * <pre>
   *由StudentResponse组成的集合
   * </pre>
   *
   * <code>repeated .cn.lcdiao.proto.StudentResponse studentResponse = 1;</code>
   */
  StudentResponseOrBuilder getStudentResponseOrBuilder(
          int index);
}
